# Generated by Django 4.2.6 on 2023-10-17 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
