# Generated by Django 4.2.6 on 2023-10-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsitem_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
