# Generated by Django 4.2.6 on 2023-10-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scraperecord_finish_time_scraperecord_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperecord',
            name='finished',
            field=models.BooleanField(default=True),
        ),
    ]
